### ISSUE TITLE
ImportError and unclear requirements.

### ISSUE THREAD

**Issue by crequena** [godisboy/DRPAN#6]
Thank you very much for the contribution and excellent work!

DRPAN it's an excellent idea that I'd like to build upon. However, I am having problems to reproduce the work.
Is there a list of requirements (preferably conda environment or dockerfile) to make sure my system is correctly set up?

Using any pytorch version newer than 0.4.1 there seems to be incompatibility issues due to some deprecated functions. However when using 0.4.1 things seem to work but when launching training running `main.py` (for any DRPAN, Pix2PixHD_DRPAN or cycleGAN_DRPA) the following happens:

> Traceback (most recent call last):
>   File "DRPAN/DRPAN/main.py", line 9, in <module>
>     from src.trainer import trainer_gan
>   File "/home/jupyter/DRPAN/DRPAN/src/trainer.py", line 11, in <module>
>     from roi_align.roi_align import RoIAlign
>   File "/home/jupyter/DRPAN/DRPAN/roi_align/roi_align.py", line 4, in <module>
>     from .crop_and_resize import CropAndResizeFunction, CropAndResize
>   File "/home/jupyter/DRPAN/DRPAN/roi_align/crop_and_resize.py", line 7, in <module>
>     from ._ext import crop_and_resize as _backend
>   File "/home/jupyter/DRPAN/DRPAN/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
>     from ._crop_and_resize import lib as _lib, ffi as _ffi
> ImportError: /home/jupyter/DRPAN/DRPAN/roi_align/_ext/crop_and_resize/_crop_and_resize.so: undefined symbol: state

How can I make sure my environment is the correctly set to reproduce your work?
Thank you so much!

**Comment by DrBrule** [comment]
I've been running into similar issues -  found the requirements in the CycleGAN_DRPAN directory : 

torch==0.4.0
torchvision==0.2.1
dominate>=2.3.1
visdom>=0.1.8.3

Some key functions used in this repo use a deprecated function in torch, so the versions can't be newer than listed here.  

However, some of the code is written for python 2.7 which presents a host of other issues.
